{% set version = "1.0.2" %}

package:
  name: ppsg
  version: {{ version }}

source:
  git_url: https://github.com/USGS-Astrogeology/PyHAT_Point_Spectra_GUI
  git_rev: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  skip: True  # [not py3k]

requirements:
  build:
    - python >=3
    - pyqt
    - numpy
    - pandas
    - scipy
    - matplotlib
    - scikit-learn
    - docutils
    - pyhat
    - setuptools
  run:
    - python >=3
    - pyqt
    - numpy
    - pandas
    - scipy
    - matplotlib
    - scikit-learn
    - docutils
    - pyhat

test:
  imports:
    - point_spectra_gui

about:
  home: https://github.com/USGS-Astrogeology/PyHAT_Point_Spectra_GUI
  license: Unlicense
