branches:
  only:
  - master
  - dev
  - dev_master_merge

version: '0.1.0.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64\\Scripts\\activate.bat"
      PYTHON_VERSION: 3.6
    - PYTHON: "C:\\Miniconda36-x64\\Scripts\\activate.bat"
      PYTHON_VERSION: 3.7

platform:
  - x64

configuration:
  - Release

install:
  - set PATH="C:\\Miniconda36-x64\\Scripts\\";"C:\\Miniconda36-x64\\";%PATH%
  - cmd: call %PYTHON%
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda install conda-build anaconda-client
  - cmd: conda create -q -n test_env python=%PYTHON_VERSION%
  - cmd: conda activate test_env
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --set ssl_verify false
  - cmd: conda install -c conda-forge numpy scipy pandas gdal scikit-learn multipledispatch pvl
  - cmd: conda install -c usgs-astrogeology plio
  - cmd: conda install pytest-cov
  # https://pythonhosted.org/CodeChat/appveyor.yml.html
  - cmd: python -m pip install -U pip
  - cmd: python -m easy_install -U setuptools

build_script:
  - cmd: python setup.py install

test_script:
  - cmd: pytest libpyhat/

on_success:
  - cmd: activate base
  - ps:
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq "") {
        $tar_glob = conda build recipe --output;
        Write-Host "tar_glob $tar_glob";
        if ($env:APPVEYOR_REPO_BRANCH -eq "dev") {
          $anaconda_label = "dev"
        } else {
          $anaconda_label = "main"
        };
        Write-Host "anaconda_label $anaconda_label";
        $parameters = '-t', "$env:CONDA_UPLOAD_TOKEN", 'upload', "$tar_glob", '-l',
                      "$anaconda_label", '--force', '--no-progress';
        & cmd /c 'anaconda 2>&1' $parameters;
      };
