# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.infolabel = QtWidgets.QLabel(self.formGroupBox)
        self.infolabel.setObjectName("infolabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.infolabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DataA_HLayout = QtWidgets.QHBoxLayout()
        self.DataA_HLayout.setObjectName("DataA_HLayout")
        self.DataA_label = QtWidgets.QLabel(self.formGroupBox)
        self.DataA_label.setObjectName("DataA_label")
        self.DataA_HLayout.addWidget(self.DataA_label)
        self.chooseDataA = QtWidgets.QComboBox(self.formGroupBox)
        self.chooseDataA.setObjectName("chooseDataA")
        self.DataA_HLayout.addWidget(self.chooseDataA)
        self.DataAMatch_label = QtWidgets.QLabel(self.formGroupBox)
        self.DataAMatch_label.setObjectName("DataAMatch_label")
        self.DataA_HLayout.addWidget(self.DataAMatch_label)
        self.chooseDataAMatch = QtWidgets.QComboBox(self.formGroupBox)
        self.chooseDataAMatch.setObjectName("chooseDataAMatch")
        self.DataA_HLayout.addWidget(self.chooseDataAMatch)
        self.verticalLayout_2.addLayout(self.DataA_HLayout)
        self.DataB_HLayout = QtWidgets.QHBoxLayout()
        self.DataB_HLayout.setObjectName("DataB_HLayout")
        self.DataB_label = QtWidgets.QLabel(self.formGroupBox)
        self.DataB_label.setObjectName("DataB_label")
        self.DataB_HLayout.addWidget(self.DataB_label)
        self.chooseDataB = QtWidgets.QComboBox(self.formGroupBox)
        self.chooseDataB.setObjectName("chooseDataB")
        self.DataB_HLayout.addWidget(self.chooseDataB)
        self.DataBMatch_label = QtWidgets.QLabel(self.formGroupBox)
        self.DataBMatch_label.setObjectName("DataBMatch_label")
        self.DataB_HLayout.addWidget(self.DataBMatch_label)
        self.chooseDataBMatch = QtWidgets.QComboBox(self.formGroupBox)
        self.chooseDataBMatch.setObjectName("chooseDataBMatch")
        self.DataB_HLayout.addWidget(self.chooseDataBMatch)
        self.verticalLayout_2.addLayout(self.DataB_HLayout)
        self.keep_spectra_checkBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.keep_spectra_checkBox.setChecked(True)
        self.keep_spectra_checkBox.setObjectName("keep_spectra_checkBox")
        self.verticalLayout_2.addWidget(self.keep_spectra_checkBox)
        self.choosemethodstext = QtWidgets.QLabel(self.formGroupBox)
        self.choosemethodstext.setObjectName("choosemethodstext")
        self.verticalLayout_2.addWidget(self.choosemethodstext)
        self.DScheckbox = QtWidgets.QCheckBox(self.formGroupBox)
        self.DScheckbox.setObjectName("DScheckbox")
        self.verticalLayout_2.addWidget(self.DScheckbox)
        self.DSlayout = QtWidgets.QVBoxLayout()
        self.DSlayout.setObjectName("DSlayout")
        self.verticalLayout_2.addLayout(self.DSlayout)
        self.PDScheckbox = QtWidgets.QCheckBox(self.formGroupBox)
        self.PDScheckbox.setObjectName("PDScheckbox")
        self.verticalLayout_2.addWidget(self.PDScheckbox)
        self.PDSlayout = QtWidgets.QVBoxLayout()
        self.PDSlayout.setObjectName("PDSlayout")
        self.verticalLayout_2.addLayout(self.PDSlayout)
        self.PDSPLScheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.PDSPLScheckBox.setObjectName("PDSPLScheckBox")
        self.verticalLayout_2.addWidget(self.PDSPLScheckBox)
        self.PDSPLSlayout = QtWidgets.QVBoxLayout()
        self.PDSPLSlayout.setObjectName("PDSPLSlayout")
        self.verticalLayout_2.addLayout(self.PDSPLSlayout)
        self.Ratiocheckbox = QtWidgets.QCheckBox(self.formGroupBox)
        self.Ratiocheckbox.setObjectName("Ratiocheckbox")
        self.verticalLayout_2.addWidget(self.Ratiocheckbox)
        self.LASSODScheckbox = QtWidgets.QCheckBox(self.formGroupBox)
        self.LASSODScheckbox.setObjectName("LASSODScheckbox")
        self.verticalLayout_2.addWidget(self.LASSODScheckbox)
        self.LASSODSlayout = QtWidgets.QVBoxLayout()
        self.LASSODSlayout.setObjectName("LASSODSlayout")
        self.verticalLayout_2.addLayout(self.LASSODSlayout)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_2)
        self.verticalLayout.addWidget(self.formGroupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(("Form"))
        self.formGroupBox.setTitle(("Calibration Transfer Cross Validation"))
        self.infolabel.setText(("Evaluates multiple methods and parameters to optimize calibration transfer. Transfer will be for A to B."))
        self.DataA_label.setText(("Data set A:"))
        self.DataAMatch_label.setText(("Column to match on:"))
        self.DataB_label.setText(("Data Set B:"))
        self.DataBMatch_label.setText(("Column to match on:"))
        self.keep_spectra_checkBox.setText(("Keep transformed spectra (uncheck for faster performance)"))
        self.choosemethodstext.setText(("Choose which methods to evaluate:"))
        self.DScheckbox.setText(("DS - Direct Standardization"))
        self.PDScheckbox.setText(("PDS - Piecewise Direct Standardization"))
        self.PDSPLScheckBox.setText(("PDS-PLS - PDS using Partial Least Squares"))
        self.Ratiocheckbox.setText(("Ratio"))
        self.LASSODScheckbox.setText(("LASSO DS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

