# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.alphaLabel = QtWidgets.QLabel(self.groupBox)
        self.alphaLabel.setObjectName("alphaLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.alphaLabel)
        self.alphaLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.alphaLineEdit.setEnabled(False)
        self.alphaLineEdit.setProperty("maximum", 999999999.0)
        self.alphaLineEdit.setProperty("value", 1.0)
        self.alphaLineEdit.setObjectName("alphaLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.alphaLineEdit)
        self.maxNumOfIterationsLabel = QtWidgets.QLabel(self.groupBox)
        self.maxNumOfIterationsLabel.setObjectName("maxNumOfIterationsLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.maxNumOfIterationsLabel)
        self.maxNumOfIterationsLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.maxNumOfIterationsLineEdit.setProperty("maximum", 999999999)
        self.maxNumOfIterationsLineEdit.setProperty("value", 1000)
        self.maxNumOfIterationsLineEdit.setObjectName("maxNumOfIterationsLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maxNumOfIterationsLineEdit)
        self.toleranceLabel = QtWidgets.QLabel(self.groupBox)
        self.toleranceLabel.setObjectName("toleranceLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.toleranceLabel)
        self.fitInterceptLabel = QtWidgets.QLabel(self.groupBox)
        self.fitInterceptLabel.setObjectName("fitInterceptLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fitInterceptLabel)
        self.fitInterceptCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.fitInterceptCheckBox.setChecked(True)
        self.fitInterceptCheckBox.setObjectName("fitInterceptCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fitInterceptCheckBox)
        self.forcePositiveCoefficientsLabel = QtWidgets.QLabel(self.groupBox)
        self.forcePositiveCoefficientsLabel.setObjectName("forcePositiveCoefficientsLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.forcePositiveCoefficientsLabel)
        self.forcePositiveCoefficientsCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.forcePositiveCoefficientsCheckBox.setObjectName("forcePositiveCoefficientsCheckBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.forcePositiveCoefficientsCheckBox)
        self.optimizeWCrossValidaitonLabel = QtWidgets.QLabel(self.groupBox)
        self.optimizeWCrossValidaitonLabel.setObjectName("optimizeWCrossValidaitonLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.optimizeWCrossValidaitonLabel)
        self.optimizeWCrossValidaitonCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.optimizeWCrossValidaitonCheckBox.setChecked(True)
        self.optimizeWCrossValidaitonCheckBox.setObjectName("optimizeWCrossValidaitonCheckBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.optimizeWCrossValidaitonCheckBox)
        self.toleranceLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.toleranceLineEdit.setProperty("decimals", 5)
        self.toleranceLineEdit.setProperty("maximum", 999999999.0)
        self.toleranceLineEdit.setProperty("value", 0.0001)
        self.toleranceLineEdit.setObjectName("toleranceLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.toleranceLineEdit)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        self.optimizeWCrossValidaitonCheckBox.toggled['bool'].connect(self.alphaLineEdit.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.alphaLineEdit, self.maxNumOfIterationsLineEdit)
        Form.setTabOrder(self.maxNumOfIterationsLineEdit, self.toleranceLineEdit)
        Form.setTabOrder(self.toleranceLineEdit, self.fitInterceptCheckBox)
        Form.setTabOrder(self.fitInterceptCheckBox, self.forcePositiveCoefficientsCheckBox)
        Form.setTabOrder(self.forcePositiveCoefficientsCheckBox, self.optimizeWCrossValidaitonCheckBox)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(("Form"))
        self.alphaLabel.setText(("Alpha"))
        self.maxNumOfIterationsLabel.setText(("Max # of iterations"))
        self.toleranceLabel.setText(("Tolerance"))
        self.fitInterceptLabel.setText(("Fit Intercept"))
        self.forcePositiveCoefficientsLabel.setText(("Force positive coefficients"))
        self.optimizeWCrossValidaitonLabel.setText(("Optimize w/ Cross Validaiton (Ignores alpha)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

