# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(287, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.fit_interceptLabel = QtWidgets.QLabel(self.formGroupBox)
        self.fit_interceptLabel.setObjectName("fit_interceptLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fit_interceptLabel)
        self.fit_intercept_listWidget = QtWidgets.QListWidget(self.formGroupBox)
        self.fit_intercept_listWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fit_intercept_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.fit_intercept_listWidget.setObjectName("fit_intercept_listWidget")
        item = QtWidgets.QListWidgetItem()
        self.fit_intercept_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fit_intercept_listWidget.addItem(item)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fit_intercept_listWidget)
        self.normalizeLabel = QtWidgets.QLabel(self.formGroupBox)
        self.normalizeLabel.setObjectName("normalizeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.normalizeLabel)
        self.normalize_list = QtWidgets.QListWidget(self.formGroupBox)
        self.normalize_list.setMaximumSize(QtCore.QSize(16777215, 50))
        self.normalize_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.normalize_list.setObjectName("normalize_list")
        item = QtWidgets.QListWidgetItem()
        self.normalize_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.normalize_list.addItem(item)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.normalize_list)
        self.n_nonzero_coefsLabel = QtWidgets.QLabel(self.formGroupBox)
        self.n_nonzero_coefsLabel.setObjectName("n_nonzero_coefsLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.n_nonzero_coefsLabel)
        self.n_nonzero_coefsLineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.n_nonzero_coefsLineEdit.setObjectName("n_nonzero_coefsLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.n_nonzero_coefsLineEdit)
        self.positiveLabel = QtWidgets.QLabel(self.formGroupBox)
        self.positiveLabel.setObjectName("positiveLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.positiveLabel)
        self.positive_list = QtWidgets.QListWidget(self.formGroupBox)
        self.positive_list.setMaximumSize(QtCore.QSize(16777215, 50))
        self.positive_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.positive_list.setObjectName("positive_list")
        item = QtWidgets.QListWidgetItem()
        self.positive_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.positive_list.addItem(item)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.positive_list)
        self.verticalLayout.addWidget(self.formGroupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(("Form"))
        self.fit_interceptLabel.setText(("Fit Intercept"))
        __sortingEnabled = self.fit_intercept_listWidget.isSortingEnabled()
        self.fit_intercept_listWidget.setSortingEnabled(False)
        item = self.fit_intercept_listWidget.item(0)
        item.setText(("True"))
        item = self.fit_intercept_listWidget.item(1)
        item.setText(("False"))
        self.fit_intercept_listWidget.setSortingEnabled(__sortingEnabled)
        self.normalizeLabel.setText(("Normalize"))
        __sortingEnabled = self.normalize_list.isSortingEnabled()
        self.normalize_list.setSortingEnabled(False)
        item = self.normalize_list.item(0)
        item.setText(("True"))
        item = self.normalize_list.item(1)
        item.setText(("False"))
        self.normalize_list.setSortingEnabled(__sortingEnabled)
        self.n_nonzero_coefsLabel.setText(("# of coefficients"))
        self.n_nonzero_coefsLineEdit.setText(("500"))
        self.positiveLabel.setText(("Force positive coefficients"))
        __sortingEnabled = self.positive_list.isSortingEnabled()
        self.positive_list.setSortingEnabled(False)
        item = self.positive_list.item(0)
        item.setText(("True"))
        item = self.positive_list.item(1)
        item.setText(("False"))
        self.positive_list.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

