# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lossLabel = QtWidgets.QLabel(self.formGroupBox)
        self.lossLabel.setObjectName("lossLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lossLabel)
        self.lossComboBox = QtWidgets.QComboBox(self.formGroupBox)
        self.lossComboBox.setObjectName("lossComboBox")
        self.lossComboBox.addItem("")
        self.lossComboBox.addItem("")
        self.lossComboBox.addItem("")
        self.lossComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lossComboBox)
        self.alphaLabel = QtWidgets.QLabel(self.formGroupBox)
        self.alphaLabel.setObjectName("alphaLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.alphaLabel)
        self.alphaDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.alphaDoubleSpinBox.setDecimals(2)
        self.alphaDoubleSpinBox.setMaximum(1.0)
        self.alphaDoubleSpinBox.setSingleStep(0.001)
        self.alphaDoubleSpinBox.setProperty("value", 0.9)
        self.alphaDoubleSpinBox.setObjectName("alphaDoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.alphaDoubleSpinBox)
        self.numEstLabel = QtWidgets.QLabel(self.formGroupBox)
        self.numEstLabel.setObjectName("numEstLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.numEstLabel)
        self.numEstSpinBox = QtWidgets.QSpinBox(self.formGroupBox)
        self.numEstSpinBox.setMaximum(999999999)
        self.numEstSpinBox.setProperty("value", 100)
        self.numEstSpinBox.setObjectName("numEstSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.numEstSpinBox)
        self.learningLabel = QtWidgets.QLabel(self.formGroupBox)
        self.learningLabel.setObjectName("learningLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.learningLabel)
        self.learningDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.learningDoubleSpinBox.setDecimals(5)
        self.learningDoubleSpinBox.setSingleStep(0.001)
        self.learningDoubleSpinBox.setProperty("value", 0.1)
        self.learningDoubleSpinBox.setObjectName("learningDoubleSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.learningDoubleSpinBox)
        self.subsampleLabel = QtWidgets.QLabel(self.formGroupBox)
        self.subsampleLabel.setObjectName("subsampleLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.subsampleLabel)
        self.subsampleDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.subsampleDoubleSpinBox.setDecimals(2)
        self.subsampleDoubleSpinBox.setMaximum(1.0)
        self.subsampleDoubleSpinBox.setSingleStep(0.01)
        self.subsampleDoubleSpinBox.setProperty("value", 1.0)
        self.subsampleDoubleSpinBox.setObjectName("subsampleDoubleSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.subsampleDoubleSpinBox)
        self.min_n_splitLabel = QtWidgets.QLabel(self.formGroupBox)
        self.min_n_splitLabel.setObjectName("min_n_splitLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.min_n_splitLabel)
        self.min_n_splitSpinBox = QtWidgets.QSpinBox(self.formGroupBox)
        self.min_n_splitSpinBox.setProperty("value", 2)
        self.min_n_splitSpinBox.setObjectName("min_n_splitSpinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.min_n_splitSpinBox)
        self.min_n_leafLabel = QtWidgets.QLabel(self.formGroupBox)
        self.min_n_leafLabel.setObjectName("min_n_leafLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.min_n_leafLabel)
        self.min_n_leafSpinBox = QtWidgets.QSpinBox(self.formGroupBox)
        self.min_n_leafSpinBox.setProperty("value", 1)
        self.min_n_leafSpinBox.setObjectName("min_n_leafSpinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.min_n_leafSpinBox)
        self.min_fractionLabel = QtWidgets.QLabel(self.formGroupBox)
        self.min_fractionLabel.setObjectName("min_fractionLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.min_fractionLabel)
        self.min_fractionDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.min_fractionDoubleSpinBox.setObjectName("min_fractionDoubleSpinBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.min_fractionDoubleSpinBox)
        self.max_depthLabel = QtWidgets.QLabel(self.formGroupBox)
        self.max_depthLabel.setObjectName("max_depthLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.max_depthLabel)
        self.max_depthSpinBox = QtWidgets.QSpinBox(self.formGroupBox)
        self.max_depthSpinBox.setMinimum(1)
        self.max_depthSpinBox.setProperty("value", 3)
        self.max_depthSpinBox.setObjectName("max_depthSpinBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.max_depthSpinBox)
        self.min_imp_decLabel = QtWidgets.QLabel(self.formGroupBox)
        self.min_imp_decLabel.setObjectName("min_imp_decLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.min_imp_decLabel)
        self.min_imp_decDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.min_imp_decDoubleSpinBox.setObjectName("min_imp_decDoubleSpinBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.min_imp_decDoubleSpinBox)
        self.verticalLayout.addWidget(self.formGroupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(("Form"))
        self.formGroupBox.setTitle(("Gradient Boosting Regression"))
        self.lossLabel.setText(("Loss Function"))
        self.lossComboBox.setItemText(0, ("Least Squares"))
        self.lossComboBox.setItemText(1, ("Least Absolute Deviation"))
        self.lossComboBox.setItemText(2, ("Huber"))
        self.lossComboBox.setItemText(3, ("Quantile"))
        self.alphaLabel.setText(("Alpha"))
        self.alphaDoubleSpinBox.setWhatsThis(("http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.BayesianRidge.html"))
        self.numEstLabel.setText(("# of estimators"))
        self.numEstSpinBox.setToolTip(("Maximum number of iterations. Default is 300."))
        self.numEstSpinBox.setWhatsThis(("http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.BayesianRidge.html"))
        self.learningLabel.setText(("Learning Rate"))
        self.learningDoubleSpinBox.setToolTip(("Stop the algorithm if w has converged. Default is 1.e-3."))
        self.learningDoubleSpinBox.setWhatsThis(("http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.BayesianRidge.html"))
        self.subsampleLabel.setText(("Subsample"))
        self.subsampleDoubleSpinBox.setWhatsThis(("http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.BayesianRidge.html"))
        self.min_n_splitLabel.setText(("Minimum # of samples to split"))
        self.min_n_splitSpinBox.setWhatsThis(("http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.BayesianRidge.html"))
        self.min_n_leafLabel.setText(("Minimum # of samples in leaf"))
        self.min_fractionLabel.setText(("Minimum weighted fraction"))
        self.max_depthLabel.setText(("Max Depth"))
        self.min_imp_decLabel.setText(("Minimum impurity decrease"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

