# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupLayout = QtWidgets.QGroupBox(Form)
        self.groupLayout.setObjectName("groupLayout")
        self.gridLayout = QtWidgets.QGridLayout(self.groupLayout)
        self.gridLayout.setObjectName("gridLayout")
        self.choosedata_predict_label = QtWidgets.QLabel(self.groupLayout)
        self.choosedata_predict_label.setObjectName("choosedata_predict_label")
        self.gridLayout.addWidget(self.choosedata_predict_label, 1, 0, 1, 1)
        self.choosedata_predict = QtWidgets.QComboBox(self.groupLayout)
        self.choosedata_predict.setObjectName("choosedata_predict")
        self.gridLayout.addWidget(self.choosedata_predict, 1, 1, 1, 1)
        self.yVariableLabel = QtWidgets.QLabel(self.groupLayout)
        self.yVariableLabel.setObjectName("yVariableLabel")
        self.gridLayout.addWidget(self.yVariableLabel, 2, 1, 1, 1)
        self.xVariableList = QtWidgets.QListWidget(self.groupLayout)
        self.xVariableList.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xVariableList.sizePolicy().hasHeightForWidth())
        self.xVariableList.setSizePolicy(sizePolicy)
        self.xVariableList.setObjectName("xVariableList")
        item = QtWidgets.QListWidgetItem()
        self.xVariableList.addItem(item)
        self.gridLayout.addWidget(self.xVariableList, 3, 0, 1, 1)
        self.yVariableList = QtWidgets.QListWidget(self.groupLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yVariableList.sizePolicy().hasHeightForWidth())
        self.yVariableList.setSizePolicy(sizePolicy)
        self.yVariableList.setObjectName("yVariableList")
        item = QtWidgets.QListWidgetItem()
        self.yVariableList.addItem(item)
        self.gridLayout.addWidget(self.yVariableList, 3, 1, 1, 1)
        self.xVariableLabel = QtWidgets.QLabel(self.groupLayout)
        self.xVariableLabel.setObjectName("xVariableLabel")
        self.gridLayout.addWidget(self.xVariableLabel, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chooseAlgorithmLabel = QtWidgets.QLabel(self.groupLayout)
        self.chooseAlgorithmLabel.setObjectName("chooseAlgorithmLabel")
        self.horizontalLayout_2.addWidget(self.chooseAlgorithmLabel)
        self.chooseAlgorithmComboBox = QtWidgets.QComboBox(self.groupLayout)
        self.chooseAlgorithmComboBox.setObjectName("chooseAlgorithmComboBox")
        self.chooseAlgorithmComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.chooseAlgorithmComboBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        self.forcepositive = QtWidgets.QCheckBox(self.groupLayout)
        self.forcepositive.setObjectName("forcepositive")
        self.gridLayout.addWidget(self.forcepositive, 7, 1, 1, 1)
        self.choosedata_train = QtWidgets.QComboBox(self.groupLayout)
        self.choosedata_train.setObjectName("choosedata_train")
        self.gridLayout.addWidget(self.choosedata_train, 0, 1, 1, 1)
        self.choosedata_train_label = QtWidgets.QLabel(self.groupLayout)
        self.choosedata_train_label.setObjectName("choosedata_train_label")
        self.gridLayout.addWidget(self.choosedata_train_label, 0, 0, 1, 1)
        self.fit_intercept = QtWidgets.QCheckBox(self.groupLayout)
        self.fit_intercept.setObjectName("fit_intercept")
        self.gridLayout.addWidget(self.fit_intercept, 8, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.n_neighbors_label = QtWidgets.QLabel(self.groupLayout)
        self.n_neighbors_label.setObjectName("n_neighbors_label")
        self.horizontalLayout.addWidget(self.n_neighbors_label)
        self.n_neighbors_spin = QtWidgets.QSpinBox(self.groupLayout)
        self.n_neighbors_spin.setMaximum(999999)
        self.n_neighbors_spin.setProperty("value", 250)
        self.n_neighbors_spin.setObjectName("n_neighbors_spin")
        self.horizontalLayout.addWidget(self.n_neighbors_spin)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(("Form"))
        self.groupLayout.setTitle(("Local Regression"))
        self.choosedata_predict_label.setText(("Choose data to predict"))
        self.yVariableLabel.setText(("Y Variable"))
        __sortingEnabled = self.xVariableList.isSortingEnabled()
        self.xVariableList.setSortingEnabled(False)
        item = self.xVariableList.item(0)
        item.setText(("Choose X"))
        self.xVariableList.setSortingEnabled(__sortingEnabled)
        self.yVariableList.setSortingEnabled(True)
        __sortingEnabled = self.yVariableList.isSortingEnabled()
        self.yVariableList.setSortingEnabled(False)
        item = self.yVariableList.item(0)
        item.setText(("Choose Y"))
        self.yVariableList.setSortingEnabled(__sortingEnabled)
        self.xVariableLabel.setText(("X Variable"))
        self.chooseAlgorithmLabel.setText(("Choose Algorithm"))
        self.chooseAlgorithmComboBox.setItemText(0, ("LASSO"))
        self.forcepositive.setText(("Force Positive"))
        self.choosedata_train_label.setText(("Choose training data"))
        self.fit_intercept.setText(("Fit Intercept"))
        self.n_neighbors_label.setText(("# of neighbors to use"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

