# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 350))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.singleShotsradioButton = QtWidgets.QRadioButton(self.groupBox)
        self.singleShotsradioButton.setText("")
        self.singleShotsradioButton.setObjectName("singleShotsradioButton")
        self.gridLayout.addWidget(self.singleShotsradioButton, 3, 1, 1, 1)
        self.averagesLabel = QtWidgets.QLabel(self.groupBox)
        self.averagesLabel.setObjectName("averagesLabel")
        self.gridLayout.addWidget(self.averagesLabel, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 12, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 13, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 13, 1, 1, 1)
        self.data_col = QtWidgets.QLineEdit(self.groupBox)
        self.data_col.setObjectName("data_col")
        self.gridLayout.addWidget(self.data_col, 10, 1, 1, 1)
        self.lookup_col_label = QtWidgets.QLabel(self.groupBox)
        self.lookup_col_label.setObjectName("lookup_col_label")
        self.gridLayout.addWidget(self.lookup_col_label, 11, 0, 1, 1)
        self.data_col_label = QtWidgets.QLabel(self.groupBox)
        self.data_col_label.setObjectName("data_col_label")
        self.gridLayout.addWidget(self.data_col_label, 10, 0, 1, 1)
        self.lookup_col = QtWidgets.QLineEdit(self.groupBox)
        self.lookup_col.setObjectName("lookup_col")
        self.gridLayout.addWidget(self.lookup_col, 11, 1, 1, 1)
        self.singleShotsLabel = QtWidgets.QLabel(self.groupBox)
        self.singleShotsLabel.setObjectName("singleShotsLabel")
        self.gridLayout.addWidget(self.singleShotsLabel, 3, 0, 1, 1)
        self.metadatapushButton = QtWidgets.QPushButton(self.groupBox)
        self.metadatapushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.metadatapushButton.setObjectName("metadatapushButton")
        self.gridLayout.addWidget(self.metadatapushButton, 5, 2, 1, 1)
        self.searchStringLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.searchStringLineEdit.setObjectName("searchStringLineEdit")
        self.gridLayout.addWidget(self.searchStringLineEdit, 0, 1, 1, 1)
        self.searchDirectoryLabel = QtWidgets.QLabel(self.groupBox)
        self.searchDirectoryLabel.setObjectName("searchDirectoryLabel")
        self.gridLayout.addWidget(self.searchDirectoryLabel, 1, 0, 1, 1)
        self.outputFileNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.outputFileNameLineEdit.setObjectName("outputFileNameLineEdit")
        self.gridLayout.addWidget(self.outputFileNameLineEdit, 14, 1, 1, 1)
        self.column_explain = QtWidgets.QLabel(self.groupBox)
        self.column_explain.setObjectName("column_explain")
        self.gridLayout.addWidget(self.column_explain, 9, 0, 1, 2)
        self.metadataFilesLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.metadataFilesLineEdit.setReadOnly(True)
        self.metadataFilesLineEdit.setObjectName("metadataFilesLineEdit")
        self.gridLayout.addWidget(self.metadataFilesLineEdit, 5, 1, 1, 1)
        self.outputFileNameLabel = QtWidgets.QLabel(self.groupBox)
        self.outputFileNameLabel.setObjectName("outputFileNameLabel")
        self.gridLayout.addWidget(self.outputFileNameLabel, 14, 0, 1, 1)
        self.metadataFilesLabel = QtWidgets.QLabel(self.groupBox)
        self.metadataFilesLabel.setObjectName("metadataFilesLabel")
        self.gridLayout.addWidget(self.metadataFilesLabel, 5, 0, 1, 1)
        self.searchDirectorypushButton = QtWidgets.QPushButton(self.groupBox)
        self.searchDirectorypushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.searchDirectorypushButton.setObjectName("searchDirectorypushButton")
        self.gridLayout.addWidget(self.searchDirectorypushButton, 1, 2, 1, 1)
        self.searchDirectoryLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.searchDirectoryLineEdit.setObjectName("searchDirectoryLineEdit")
        self.gridLayout.addWidget(self.searchDirectoryLineEdit, 1, 1, 1, 1)
        self.searchStringLabel = QtWidgets.QLabel(self.groupBox)
        self.searchStringLabel.setObjectName("searchStringLabel")
        self.gridLayout.addWidget(self.searchStringLabel, 0, 0, 1, 1)
        self.averagesradioButton = QtWidgets.QRadioButton(self.groupBox)
        self.averagesradioButton.setText("")
        self.averagesradioButton.setChecked(True)
        self.averagesradioButton.setObjectName("averagesradioButton")
        self.gridLayout.addWidget(self.averagesradioButton, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 3)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(("Form"))
        self.groupBox.setTitle(("Read ChemCam Data"))
        self.averagesLabel.setText(("Averages"))
        self.label.setText(("Data set name"))
        self.lineEdit.setText(("ChemCam"))
        self.data_col.setText(("sclock"))
        self.lookup_col_label.setText(("Lookup table column"))
        self.data_col_label.setText(("Data column"))
        self.lookup_col.setText(("Spacecraft Clock"))
        self.singleShotsLabel.setText(("Single Shots"))
        self.metadatapushButton.setText(("..."))
        self.searchStringLineEdit.setText(("*ccs*.csv"))
        self.searchDirectoryLabel.setText(("Search directory:"))
        self.outputFileNameLineEdit.setText(("ChemCam.csv"))
        self.column_explain.setText(("Columns to match on when merging data with metadata:"))
        self.outputFileNameLabel.setText(("Output file name:"))
        self.metadataFilesLabel.setText(("Metadata file(s):"))
        self.searchDirectorypushButton.setText(("..."))
        self.searchStringLabel.setText(("Search String:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

