# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.choosemethodstext = QtWidgets.QLabel(self.formGroupBox)
        self.choosemethodstext.setObjectName("choosemethodstext")
        self.verticalLayout_2.addWidget(self.choosemethodstext)
        self.ARDcheckbox = QtWidgets.QCheckBox(self.formGroupBox)
        self.ARDcheckbox.setObjectName("ARDcheckbox")
        self.verticalLayout_2.addWidget(self.ARDcheckbox)
        self.ARDLayout = QtWidgets.QVBoxLayout()
        self.ARDLayout.setObjectName("ARDLayout")
        self.verticalLayout_2.addLayout(self.ARDLayout)
        self.BRRcheckbox = QtWidgets.QCheckBox(self.formGroupBox)
        self.BRRcheckbox.setObjectName("BRRcheckbox")
        self.verticalLayout_2.addWidget(self.BRRcheckbox)
        self.BRRlayout = QtWidgets.QVBoxLayout()
        self.BRRlayout.setObjectName("BRRlayout")
        self.verticalLayout_2.addLayout(self.BRRlayout)
        self.ENetcheckbox = QtWidgets.QCheckBox(self.formGroupBox)
        self.ENetcheckbox.setObjectName("ENetcheckbox")
        self.verticalLayout_2.addWidget(self.ENetcheckbox)
        self.ENetlayout = QtWidgets.QVBoxLayout()
        self.ENetlayout.setObjectName("ENetlayout")
        self.verticalLayout_2.addLayout(self.ENetlayout)
        self.LARScheckbox = QtWidgets.QCheckBox(self.formGroupBox)
        self.LARScheckbox.setObjectName("LARScheckbox")
        self.verticalLayout_2.addWidget(self.LARScheckbox)
        self.LARSlayout = QtWidgets.QVBoxLayout()
        self.LARSlayout.setObjectName("LARSlayout")
        self.verticalLayout_2.addLayout(self.LARSlayout)
        self.LASSOcheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.LASSOcheckBox.setObjectName("LASSOcheckBox")
        self.verticalLayout_2.addWidget(self.LASSOcheckBox)
        self.LASSOlayout = QtWidgets.QVBoxLayout()
        self.LASSOlayout.setObjectName("LASSOlayout")
        self.verticalLayout_2.addLayout(self.LASSOlayout)
        self.OLScheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.OLScheckBox.setObjectName("OLScheckBox")
        self.verticalLayout_2.addWidget(self.OLScheckBox)
        self.OLSLayout = QtWidgets.QVBoxLayout()
        self.OLSLayout.setObjectName("OLSLayout")
        self.verticalLayout_2.addLayout(self.OLSLayout)
        self.OMPcheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.OMPcheckBox.setObjectName("OMPcheckBox")
        self.verticalLayout_2.addWidget(self.OMPcheckBox)
        self.OMPlayout = QtWidgets.QVBoxLayout()
        self.OMPlayout.setObjectName("OMPlayout")
        self.verticalLayout_2.addLayout(self.OMPlayout)
        self.PLScheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.PLScheckBox.setObjectName("PLScheckBox")
        self.verticalLayout_2.addWidget(self.PLScheckBox)
        self.PLSLayout = QtWidgets.QVBoxLayout()
        self.PLSLayout.setObjectName("PLSLayout")
        self.verticalLayout_2.addLayout(self.PLSLayout)
        self.RidgecheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.RidgecheckBox.setObjectName("RidgecheckBox")
        self.verticalLayout_2.addWidget(self.RidgecheckBox)
        self.Ridgelayout = QtWidgets.QVBoxLayout()
        self.Ridgelayout.setObjectName("Ridgelayout")
        self.verticalLayout_2.addLayout(self.Ridgelayout)
        self.SVRcheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.SVRcheckBox.setObjectName("SVRcheckBox")
        self.verticalLayout_2.addWidget(self.SVRcheckBox)
        self.SVRlayout = QtWidgets.QVBoxLayout()
        self.SVRlayout.setObjectName("SVRlayout")
        self.verticalLayout_2.addLayout(self.SVRlayout)
        self.LocalcheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.LocalcheckBox.setObjectName("LocalcheckBox")
        self.verticalLayout_2.addWidget(self.LocalcheckBox)
        self.Locallayout = QtWidgets.QVBoxLayout()
        self.Locallayout.setObjectName("Locallayout")
        self.verticalLayout_2.addLayout(self.Locallayout)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chooseDataLabel = QtWidgets.QLabel(self.formGroupBox)
        self.chooseDataLabel.setObjectName("chooseDataLabel")
        self.horizontalLayout_3.addWidget(self.chooseDataLabel)
        self.chooseDataComboBox = QtWidgets.QComboBox(self.formGroupBox)
        self.chooseDataComboBox.setObjectName("chooseDataComboBox")
        self.horizontalLayout_3.addWidget(self.chooseDataComboBox)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.xVariableList = QtWidgets.QListWidget(self.formGroupBox)
        self.xVariableList.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xVariableList.sizePolicy().hasHeightForWidth())
        self.xVariableList.setSizePolicy(sizePolicy)
        self.xVariableList.setObjectName("xVariableList")
        item = QtWidgets.QListWidgetItem()
        self.xVariableList.addItem(item)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.xVariableList)
        self.yVariableList = QtWidgets.QListWidget(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yVariableList.sizePolicy().hasHeightForWidth())
        self.yVariableList.setSizePolicy(sizePolicy)
        self.yVariableList.setObjectName("yVariableList")
        item = QtWidgets.QListWidgetItem()
        self.yVariableList.addItem(item)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.yVariableList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yMinLabel = QtWidgets.QLabel(self.formGroupBox)
        self.yMinLabel.setObjectName("yMinLabel")
        self.horizontalLayout.addWidget(self.yMinLabel)
        self.yMinDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.yMinDoubleSpinBox.setObjectName("yMinDoubleSpinBox")
        self.horizontalLayout.addWidget(self.yMinDoubleSpinBox)
        self.yMaxLabel = QtWidgets.QLabel(self.formGroupBox)
        self.yMaxLabel.setObjectName("yMaxLabel")
        self.horizontalLayout.addWidget(self.yMaxLabel)
        self.yMaxDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.yMaxDoubleSpinBox.setObjectName("yMaxDoubleSpinBox")
        self.horizontalLayout.addWidget(self.yMaxDoubleSpinBox)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.infolabel = QtWidgets.QLabel(self.formGroupBox)
        self.infolabel.setObjectName("infolabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.infolabel)
        self.xVariableLabel = QtWidgets.QLabel(self.formGroupBox)
        self.xVariableLabel.setObjectName("xVariableLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.xVariableLabel)
        self.yVariableLabel = QtWidgets.QLabel(self.formGroupBox)
        self.yVariableLabel.setObjectName("yVariableLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.yVariableLabel)
        self.verticalLayout.addWidget(self.formGroupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(("Form"))
        self.formGroupBox.setTitle(("Regression Cross Validation"))
        self.choosemethodstext.setText(("Choose which methods to evaluate:"))
        self.ARDcheckbox.setText(("ARD - Automatic Relevance Determination"))
        self.BRRcheckbox.setText(("BRR - Bayesian Ridge Regression"))
        self.ENetcheckbox.setText(("Elastic Net"))
        self.LARScheckbox.setText(("LARS - Least Angle Regression"))
        self.LASSOcheckBox.setText(("LASSO - Least Absolute Shrinkage and Selection Operator"))
        self.OLScheckBox.setText(("OLS - Ordinary Least Squares"))
        self.OMPcheckBox.setText(("OMP - Orthogonal Matching Pursuit"))
        self.PLScheckBox.setText(("PLS - Partial Least Squares"))
        self.RidgecheckBox.setText(("Ridge"))
        self.SVRcheckBox.setText(("SVR - Support Vector Regression"))
        self.LocalcheckBox.setText(("Local Regression"))
        self.chooseDataLabel.setText(("Choose Data"))
        __sortingEnabled = self.xVariableList.isSortingEnabled()
        self.xVariableList.setSortingEnabled(False)
        item = self.xVariableList.item(0)
        item.setText(("Choose X"))
        self.xVariableList.setSortingEnabled(__sortingEnabled)
        self.yVariableList.setSortingEnabled(True)
        __sortingEnabled = self.yVariableList.isSortingEnabled()
        self.yVariableList.setSortingEnabled(False)
        item = self.yVariableList.item(0)
        item.setText(("Choose Y"))
        self.yVariableList.setSortingEnabled(__sortingEnabled)
        self.yMinLabel.setText(("Y Min"))
        self.yMaxLabel.setText(("Y Max"))
        self.infolabel.setText(("Evaluates multiple methods and parameters to optimize regression."))
        self.xVariableLabel.setText(("X Variable"))
        self.yVariableLabel.setText(("Y Variable"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

